export const REST_APIS = {
  sendOTP: '/api/registration/consumer-mobile',
  verifyOTP: '/api/registration/verification/consumer-mobile',
  bookService: '/api/web/sell/pickup',
  registerConsumer: '/api/websiteRegistration/consumer',
  getServiceCategories: '/api/web/categories/distinct-product-categories/:city?includeIds=true',
  getSubServiceCategories: '/api/web/area/prices/consumer/service',
  addressCategories: '/api/consumer/categories',
  allCities: '/api/city/getAll',
  faqs: '/api/consumer/faqs',
  registerServicePartner: '/api/add-lead-web',
  uploadResume: '/api/upload-image',
  privacyPolicy: '/api/info/privacy-policy',
  termsAndConditions: '/api/info/terms-and-conditions',
  cancellationPolicy: '/api/info/cancellation-policy',
  callMeBack: '/api/consumer/triggercall/:mobileNo',
  createOrder: '/api/billdesk/order/create',
  retrieveOrder: '/api/billdesk/transaction/retrieve',
  enablePrePayments: '/api/appointment-properties/enable-pre-payments/:city',
  checkServiceArea: '/api/get/area/:city/:lat/:lng',
};
